export const CONFIG_VAR = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  // STRIPE
  STRIPE_API_SECRET_KEY: 'STRIPE_API_SECRET_KEY',
  STRIPE_PUBLIC_KEY: 'STRIPE_PUBLIC_KEY',

  // ADMIN ACCOUNT
  DEFAULT_ADMIN_USERNAME: 'DEFAULT_ADMIN_USERNAME',
  DEFAULT_ADMIN_PASSWORD: 'DEFAULT_ADMIN_PASSWORD',
  DEFAULT_ADMIN_EMAIL: 'DEFAULT_ADMIN_EMAIL',

  // MONGODB
  MONGO_DB_URI: 'MONGO_DB_URI',

  // JWT
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',

  // REDIS
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',

  // SENDGRID
  SENDGRID_API_KEY: 'SENDGRID_API_KEY',

  // CLOUDINARY
  CLOUDINARY_NAME: 'CLOUDINARY_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',

  // FIREBASE
  FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
  FIREBASE_PRIVATE_KEY: 'FIREBASE_PRIVATE_KEY',
  FIREBASE_CLIENT_EMAIL: 'FIREBASE_CLIENT_EMAIL',

  //S3
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_ENDPOINT: 'AWS_ENDPOINT',
  AWS_REGION: 'AWS_REGION',
  AWS_BUCKET_S3: 'AWS_BUCKET_S3',
};
